/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: '#ffffff',
        'bg-soft': '#f8f8fc',
        surface: '#ffffff',
        'surface-muted': '#f8f8fc',
        'surface-subtle': '#eef2f8',
        ink: '#212529',
        'ink-2': '#192f3f',
        muted: '#6c757d',
        subtle: '#adb5bd',
        disabled: '#cbd5e1',
        border: '#e9edf5',
        'border-strong': '#e2e8f0',
        'primary-1': '#ee53ff',
        'primary-2': '#31e1f8',
        'primary-3': '#8371f3',
        'primary-solid': '#8b5cf6',
        success: '#1f9d63',
        'success-soft': '#edf9f2',
        warning: '#c88618',
        'warning-soft': '#fff7e8',
        error: '#cc425c',
        'error-soft': '#fff0f3',
        info: '#356ae6',
        'info-soft': '#eef3ff',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', '"Inter"', '"SF Pro Text"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
        display: ['"Instrument Serif"', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', '"SFMono-Regular"', 'monospace'],
      },
      fontSize: {
        'display-xl': '96px',
        'display-lg': '64px',
        'display-md': '48px',
        'h1': '40px',
        'h2': '32px',
        'h3': '24px',
        'h4': '20px',
        'body-lg': '18px',
        'body': '16px',
        'body-sm': '14px',
        'caption': '12px',
      },
      borderRadius: {
        'xs': '8px',
        'sm': '10px',
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        'pill': '999px',
      },
      boxShadow: {
        'xs': '0 1px 2px rgba(16, 18, 25, 0.04)',
        'sm': '0 4px 24px rgba(0, 0, 0, 0.04)',
        'md': '0 8px 40px rgba(0, 0, 0, 0.08)',
        'lg': '0 24px 64px rgba(168, 85, 247, 0.12)',
        'brand': '0 6px 24px rgba(168, 85, 247, 0.28)',
      },
      maxWidth: {
        'marketing': '1200px',
        'product': '1440px',
      },
    },
  },
  plugins: [],
}
